import { FrameShape, FaceShape, Occasion } from '../types/database';

export const DEFAULT_FRAME_SHAPES: FrameShape[] = [
  {
    id: 'shape-round',
    name: 'Round',
    slug: 'round',
    description: 'Soft circular curves defining timeless intellectual silhouettes',
    sort_order: 1,
    active: true,
  },
  {
    id: 'shape-square',
    name: 'Square',
    slug: 'square',
    description: 'Defined angles and structured horizontal architectural lines',
    sort_order: 2,
    active: true,
  },
  {
    id: 'shape-hexagonal',
    name: 'Hexagonal',
    slug: 'hexagonal',
    description: 'Architectural geometric contours with modern precision',
    sort_order: 3,
    active: true,
  },
  {
    id: 'shape-aviator',
    name: 'Aviator',
    slug: 'aviator',
    description: 'Double-bridge teardrop silhouette with classic presence',
    sort_order: 4,
    active: true,
  },
  {
    id: 'shape-cat-eye',
    name: 'Cat-Eye',
    slug: 'cat-eye',
    description: 'Uplifted outer rim angles creating sculptural drama',
    sort_order: 5,
    active: true,
  },
  {
    id: 'shape-browline',
    name: 'Browline',
    slug: 'browline',
    description: 'Prominent upper acetate rims balanced with sleek lower frame',
    sort_order: 6,
    active: true,
  },
  {
    id: 'shape-shield-wrap',
    name: 'Shield / Wrap',
    slug: 'shield-wrap',
    description: 'Continuous aerodynamic curve engineered for dynamic lifestyle',
    sort_order: 7,
    active: true,
  },
  {
    id: 'shape-oval',
    name: 'Oval',
    slug: 'oval',
    description: 'Elongated soft curves offering balanced proportions',
    sort_order: 8,
    active: true,
  },
];

export const DEFAULT_FACE_SHAPES: FaceShape[] = [
  {
    id: 'face-oval',
    name: 'Oval Face',
    slug: 'oval',
    description: 'Balanced symmetry suited for virtually all frame silhouettes',
    sort_order: 1,
    active: true,
  },
  {
    id: 'face-round',
    name: 'Round Face',
    slug: 'round',
    description: 'Complements angular, geometric, and square frames for definition',
    sort_order: 2,
    active: true,
  },
  {
    id: 'face-square',
    name: 'Square Face',
    slug: 'square',
    description: 'Harmonizes with round, oval, and curved silhouettes to soften jawline',
    sort_order: 3,
    active: true,
  },
  {
    id: 'face-heart',
    name: 'Heart Face',
    slug: 'heart',
    description: 'Accented by light bottom frames, aviators, and round contours',
    sort_order: 4,
    active: true,
  },
  {
    id: 'face-diamond',
    name: 'Diamond Face',
    slug: 'diamond',
    description: 'Emphasized by browlines, cat-eyes, and oval proportions',
    sort_order: 5,
    active: true,
  },
  {
    id: 'face-oblong',
    name: 'Oblong Face',
    slug: 'oblong',
    description: 'Balanced by tall lenses and wider geometric frames',
    sort_order: 6,
    active: true,
  },
];

export const DEFAULT_OCCASIONS: Occasion[] = [
  {
    id: 'occ-daily',
    name: 'Daily Wear',
    slug: 'daily',
    description: 'Effortless versatility for everyday creative pursuits',
    sort_order: 1,
    active: true,
  },
  {
    id: 'occ-business',
    name: 'Business & Formal',
    slug: 'business',
    description: 'Refined structural elegance for leadership and client meetings',
    sort_order: 2,
    active: true,
  },
  {
    id: 'occ-weekend',
    name: 'Casual Weekend',
    slug: 'weekend',
    description: 'Relaxed sophistication for gallery walks and weekend cafes',
    sort_order: 3,
    active: true,
  },
  {
    id: 'occ-travel',
    name: 'Outdoor & Travel',
    slug: 'travel',
    description: 'High-contrast statement style engineered for sun and movement',
    sort_order: 4,
    active: true,
  },
  {
    id: 'occ-screen',
    name: 'Screen & Digital Work',
    slug: 'screen',
    description: 'Lightweight ergonomic comfort optimized for extended device focus',
    sort_order: 5,
    active: true,
  },
  {
    id: 'occ-statement',
    name: 'Statement Event',
    slug: 'statement',
    description: 'Striking architectural silhouettes curated for gala and evening wear',
    sort_order: 6,
    active: true,
  },
];
